In [2]:
import numpy as np 

array = np.array([1 ,2 , 3]) 

print(array + 1)             #Scalar Arithmetic
print(array - 2)
print(array * 3)
print(array / 4)
print(array ** 2 )

[2 3 4]
[-1  0  1]
[3 6 9]
[0.25 0.5  0.75]
[1 4 9]


In [3]:
#Vectorized math functions 
import numpy as np 

array = np.array([1 ,2 ,3])

print(np.sqrt(array)) 

[1.         1.41421356 1.73205081]


In [5]:
import numpy as np

array = ([1.0 ,2.5 ,3.9])

print(np.round(array))
print(np.pi)

[1. 2. 4.]
3.141592653589793


In [6]:
import numpy as np 

radii = np.array([1, 2, 3])
print(np.pi * radii **2)  # area of circle

[ 3.14159265 12.56637061 28.27433388]


In [8]:
#Element-wise arithmetic
import numpy as np 

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

print(array1 + array2)
print(array1 - array2)
print(array1 * array2)
print(array1 / array2)
print(array1 ** array2)
     

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [10]:
#Comparison operators
import numpy as np

scores = np.array([45, 65, 95, 24, 36, 82]) 

scores[scores < 50] = 0
print(scores)

[ 0 65 95  0  0 82]


In [16]:
import numpy as np 

array1 = np.array([[1, 2, 3, 4]])
array2 = np.array([[1],[2],[3],[4]])

print(array1.shape)
print(array2.shape)

print(array1 * array2)

(1, 4)
(4, 1)
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


In [20]:
import numpy as np 

array1 = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12], 
                   [13, 14, 15, 16]])

array2 = np.array([[1],[2],[3],[4]])

print(array1 * array2)

[[ 1  2  3  4]
 [10 12 14 16]
 [27 30 33 36]
 [52 56 60 64]]


In [23]:
import numpy as np

array1 = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])
array2 = np.array([[1],[2],[3],[4],[5],[6],[7],[8],[9],[10]])

print(array1 * array2)

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [26]:
#Aggregate Functions
import numpy as np

array = np.array([[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 10]])

print('sum:',np.sum(array))
print('mean:',np.mean(array))
print('Standard Deviation: ',np.std(array))
print('variance:',np.var(array))
print('Minimum:',np.min(array))
print('Maximum:',np.max(array))
print('position of min:',np.argmin(array))
print('position of max:',np.argmax(array))

sum: 55
mean: 5.5
Standard Deviation:  2.8722813232690143
variance: 8.25
Minimum: 1
Maximum: 10
position of min: 0
position of max: 9


In [27]:
import numpy as np

array = np.array([[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 10]])

print(np.sum(array, axis=1))


[15 40]


In [34]:
#Filtering
import numpy as np

ages = np.array([[21, 65, 18, 30, 19, 17, 54],
                 [45, 25, 22, 25, 39, 19, 99]])

teenagers = ages[ages < 18]
adults = ages[(ages >= 18) & (ages < 65)]
seniors = ages[(ages >= 65)]

print(teenagers)
print(adults)
print(seniors)

[17]
[21 18 30 19 54 45 25 22 25 39 19]
[65 99]


In [36]:
import numpy as np

ages = np.array([[21, 65, 18, 30, 19, 17, 54, 16],
                 [45, 25, 22, 25, 39, 19, 99, 15]])

adults = np.where(ages >= 18, ages, 0)
print(adults)

[[21 65 18 30 19  0 54  0]
 [45 25 22 25 39 19 99  0]]


In [40]:
#random no. generating
import numpy as np 

rng = np.random.default_rng()

print(rng.integers(low=1, high=101, size=(2, 2)))

[[52 38]
 [88 15]]


In [52]:
import numpy as np

print(np.random.uniform(low=-1, high=1, size=(3,2)))


[[-0.59070273  0.23854193]
 [-0.40069065 -0.46634545]
 [ 0.24226767  0.05828419]]


In [62]:
import numpy as np

rng = np.random.default_rng()

array = np.array([1 ,2 ,3 ,4 ,5])
rng.shuffle(array)
print(array)

[4 5 3 2 1]


In [63]:
import numpy as np

fruits = np.array(["apple","mango","grapes","banana"])
fruits = rng.choice(fruits, size = (2, 2))
print(fruits)

[['grapes' 'apple']
 ['banana' 'mango']]
