In [4]:
#Introduction to NumPy
import numpy as np
array = np.array([1, 2, 3, 4, 5])
print(array)

[1 2 3 4 5]


In [5]:
import numpy as np
array = np.array([1, 2, 3, 4, 5])
array = array * 2
print(array)

[ 2  4  6  8 10]


In [6]:
#Multidimentional arrays
#1-Dimensional array 

import numpy as np

array = np.array(['A','B','C'])

print(array.ndim)

1


In [8]:
#2-Dimensional array 

import numpy as np

array = np.array([['A','B','C'],
                  ['D','E','F'],
                  ['G','H','I']])

print(array.ndim)

2


In [10]:
import numpy as np

array = np.array([[['A','B','C'],['D','E','F'],['G','H','I']],
                  [['J','K','L'],['M','N','O'],['P','Q','R']],
                  [['S','T','U'],['V','W','X'],['Y','Z','A']]])

print(array.ndim)

3


In [11]:
#shape of the array
import numpy as np

array = np.array([[['A','B','C'],['D','E','F'],['G','H','I']],
                  [['J','K','L'],['M','N','O'],['P','Q','R']],
                  [['S','T','U'],['V','W','X'],['Y','Z','A']]])

print(array.shape)

(3, 3, 3)


In [17]:
#accessing the array using index
import numpy as np

array = np.array([[['A','B','C'],['D','E','F'],['G','H','I']],
                  [['J','K','L'],['M','N','O'],['P','Q','R']],
                  [['S','T','U'],['V','W','X'],['Y','Z',' ']]])

print(array[0][0][0])
print(array[0,2,0])

A
G


In [18]:
#Writing name using index
import numpy as np

array = np.array([[['A','B','C'],['D','E','F'],['G','H','I']],
                  [['J','K','L'],['M','N','O'],['P','Q','R']],
                  [['S','T','U'],['V','W','X'],['Y','Z',' ']]])

name = array[1,1,0]+array[0,0,0]+array[1,1,1]+array[1,1,2]+array[1,0,0]
print(name)

MANOJ


In [23]:
 #Slicing
import numpy as np 

array = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12],
                  [13,14,15,16]])

print(array[0]) #slicing row
print(array[1])
print(array[3])

[1 2 3 4]
[5 6 7 8]
[13 14 15 16]


In [24]:
import numpy as np 

array = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12],
                  [13,14,15,16]])

print(array[0]) #slicing row
print(array[1])
print(array[3])

[1 2 3 4]
[5 6 7 8]
[13 14 15 16]


In [31]:
import numpy as np 

array = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12],
                  [13,14,15,16]])

print(array[0:2]) # slicing Starting from at row 0 and ending at row 2

[[1 2 3 4]
 [5 6 7 8]]


In [40]:
import numpy as np 

array = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12],
                  [13,14,15,16]])

print(array[0:2])
print(array[1:3]) 

[[1 2 3 4]
 [5 6 7 8]]
[[ 5  6  7  8]
 [ 9 10 11 12]]


In [46]:
import numpy as np 

array = np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12],
                  [13,14,15,16]])

print(array[0:1:-1])


[]
